/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 centeredlungs.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/centeredlungs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.003']} position={[-0.197, -0.022, 0.07]} scale={0.152} />
      <group position={[-0.254, 1.702, 0]} scale={0.152}>
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Circle002.geometry} material={materials['Material.004']} position={[-0.197, -0.022, 0.07]} scale={0.152} />
    </group>
  )
}

useGLTF.preload('/centeredlungs.glb')
