/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 teeth.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/teeth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus002.geometry} material={materials.gums} position={[-0.825, 0.481, -1.375]} rotation={[Math.PI, -0.983, Math.PI]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.teeth} position={[0.733, 0.514, -0.134]} rotation={[Math.PI, -0.983, 3.059]} scale={-0.17} />
      <mesh geometry={nodes.Torus001.geometry} material={materials.gums} position={[-0.775, -0.596, -1.34]} rotation={[-Math.PI, -0.983, 0]} scale={0.939} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.teeth} position={[0.857, -0.628, -0.423]} rotation={[Math.PI, -0.983, -0.083]} scale={-0.159} />
      <mesh geometry={nodes.Torus003.geometry} material={materials['Material.001']} position={[-0.825, 0.436, -1.375]} rotation={[Math.PI, -0.983, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/teeth.glb')
