/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 lungs.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lungs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[-0.473, 1.249, 0]} scale={0.207} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[0.412, 1.249, 0]} scale={0.207} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Material.002']} position={[-0.003, 1.319, -3.428]} scale={0.119} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.001']} position={[0, 1.497, 0]} scale={0.152} />
    </group>
  )
}

useGLTF.preload('/lungs.glb')
