/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 newlungs.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/newlungs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle001.geometry} material={materials['Material.001']} position={[0, 1.497, 0]} scale={0.152} />
      <mesh geometry={nodes.Circle002.geometry} material={materials.Material} position={[0, 1.497, 0]} scale={0.152} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Material.005']} position={[0, 1.497, 0]} scale={0.152} />
    </group>
  )
}

useGLTF.preload('/newlungs.glb')
