export const cancerText = ""

export const Texts = {
    Asthma: "Smoking is not only one of the main factors contributing to the development of bronchial asthma, but also significantly aggravates its course. Tobacco smoke, irritating the respiratory tract, is actively involved in the formation of bronchial hyperreactivity - a condition against which asthma develops.   Smokers are almost 4 times more likely to develop asthma than non-smokers. Asthmatic smokers respond worse to treatment with standard doses of steroids, which forces the doctor to constantly increase them. This leads to the development of side effects - a pronounced weakening of the immune response, a violation of metabolic processes."
    ,LungsCancer: "Tobacco smoke contains carcinogens, which at times increase the likelihood of degeneration of body cells with the formation of a cancerous tumor. Once in the body, these substances damage the DNA of healthy cells. Cell activity becomes uncontrollable, the process of pathological uncontrolled division begins, which leads to the formation of cancerous tumors that are difficult to treat. The risk of dependence on the increase in the number of cigarettes, experience, the number of cigarettes that a person smokes per day."
    ,LungCollapse: "A collapsed lung (pneumothorax) occurs when the space around the lungs fills with air, forcing the lungs to descend. In some severe cases, both lungs may collapse completely, requiring emergency medical attention. Tobacco smoking significantly increases the risk of PSP and also increases the likelihood of re-collapse of the lung. If your lungs collapse, you will experience sudden, sharp chest pain, shortness of breath, heart palpitations, coughing, and other symptoms depending on the severity of the condition. In some cases, but not always, it becomes difficult to breathe. If you smoke, your healthcare professional will strongly recommend that you stop smoking after PSP."
    ,Tuberculosis: "Tuberculosis is an infectious disease that is more common in the lungs and raises the suspicion of allergies. It is measured in the air when infected people cough, sneeze, or expectorate. Smoking increases the likelihood of developing tuberculosis by 2-4 times. The frequency of smoking in patients with pulmonary tuberculosis reaches 95%. Smoking depresses the immune system and other defense mechanisms. When smoking, irritation of the mucous membrane of the lungs occurs, which is a favorable factor for the progression of tuberculosis. Studies have found a strong association of tobacco smoking with the likely common form of pulmonary tuberculosis. Smoking increases the likelihood of developing tuberculosis by 2-4 times. The frequency of smoking in patients with pulmonary tuberculosis reaches 95%. Smoking depresses the immune system and other defense mechanisms. When smoking, irritation of the mucous membrane of the lungs occurs, which is a favorable factor for the progression of tuberculosis. Studies have found a strong association between tobacco smoking and a likely common form of pulmonary tuberculosis."
    ,Tartar: "Tartar forms when soft plaque reaches a high degree of density and mineralizes. It deposits under and above the gums, causing inflammation and making teeth unattractive. Tartar provokes bad breath, gums begin to bleed, dark spots appear on the visible surfaces of the teeth. It can’t be removed with a brush. Smoker's plaque consists of nicotine tar, tar, ammonia and phenolic compounds that remain on the teeth. All these substances settle very firmly on the surface of the teeth, negatively affecting the tooth enamel and contributing to a change in its color. Smoker's plaque is practically not removed with a toothbrush when brushing your teeth. Tartar can only be removed during professional hygiene." 
    ,YellowTeeth: "Smoking harms the condition of tooth enamel. They acquire a yellow-brown tint that does not disappear even with daily use of whitening pastes. Moreover, tobacco smoke changes the composition of saliva, disrupting the acid-base balance and reducing bactericidal properties. Particles of tobacco tar settle on the teeth, which leads to their yellowing. The high temperature of the smoke alternates with cooled inhaled air, which leads to the formation of microcracks on the surface of the enamel. The stability of staining depends on various factors, including the frequency of tobacco smoking. Tobacco smoke in the mouth destroys the integrity of the enamel and kills beneficial microorganisms. The longer and more intensely you smoke, the harder it is to whiten your teeth."
    ,mouthCancer: "Tobacco smoking releases toxins into the mouth, as well as irritating chemicals that alter the lining of oral tissues. Hot smoke irritates and burns the mucous membrane, chemicals inhibit the formation of an enzyme that disinfects the oral cavity. The mucosa becomes drier, saliva lingers less on ulcers, and mucosal renewal does not occur. Cancer of the oral mucosa may develop. Studies show that heavy smokers are 6 times more likely to develop oral cancer than non-smokers. The best method of prevention is to avoid smoking cigarettes and pipes, chewing and sniffing tobacco. People who stop using tobacco, even after years of smoking, greatly reduce their risk of oral cancer."
    ,GumDiseases: "Nicotine constricts blood vessels and capillaries, which leads to weakening of the gum tissue. The poisonous composition of cigarettes dries, dehydrates and reduces the required oxygen content. The tissues of the oral cavity atrophy, exfoliate and cease to protect the root of the tooth. Studies in many countries have shown that when people of the same age group are compared, smokers are more likely to develop loose teeth, more likely to lose the bone that supports teeth, and more likely to lose teeth. Gingivitis and Periodontitis are the main two possible inflammations. This eventually leads to tooth loss, which is twice as common in smokers as in non-smokers."
    ,Stomatitis: "Stomatitis is a protective reaction of the oral mucosa to the long-term toxic effects of tobacco smoke products during smoking or chewing. This is an inflammation of the oral mucosa that occurs on the tongue, gums, palate, lips, cheeks. The disease manifests itself in various forms. Pathology can occur both in the form of a slight redness, and with the formation of a large number of ulcers. At the same time, it causes significant discomfort. Often, stomatitis in the palate, gums, cheeks significantly complicates eating, disrupts speech and reduces the overall standard of living of the patient.  The risk group includes smokers. The first symptom of the disease is redness of the mucous membrane. Usually it has a round or oval white color. Over time, pain appears. Usually such defects are formed on the tongue, cheeks and lips."
    ,LossOfTaste: "This effect affects the quality of life and when smoking cigarettes it is impossible to get rid of it. The product of cigarette smoking is smoke, which contains many harmful substances along with combustion products and large particles of tobacco. All these combustion products tend to clog the pores of the taste buds. Smoking also blunts the olfactory function, which reduces the ability to pick up food flavors and also affects the perception of food. The only way to get rid of this negative effect of smoking is to stop smoking cigarettes. The change in taste is gradual. The smoker does not even immediately realize that he does not experience such pleasure from food as before. The good news is that you can regain lost functions if you stop smoking. Many ex-smokers note that within a couple of days without nicotine, the smells and tastes of food become much stronger and more distinguishable."
    ,Plaque: "Plaque is nothing more than bacteria that accumulates on the tongue. A healthy non-smoker may normally have a thin white coating through which the structure of the tongue is visible - the result of the accumulation of bacteria of the natural microflora that live in the oral cavity and feed on food debris and epithelium.  But if the plaque becomes opaque and dense, acquires a yellow or gray tint - this indicates the multiplication of pathogenic bacteria, which, in turn, indicates possible health problems. Smokers form a dense yellowish (brown) coating on the tongue, which is difficult to remove at home. The symptom appears as a result of exposure to smoking tar. The most direct connection between smoking and the occurrence of plaque is that toxic tobacco smoke disrupts the balance of microflora and leads to the death of beneficial microorganisms, which are replaced by pathogenic bacteria - for example, Candida fungi that cause candidiasis. The plaque is white or grayish in color."
    ,BadSmell: "Smoking causes persistent bad breath - halitosis. The cause of bad breath is the persistence and exhalation of tobacco smoke. Nicotine, tar and other substances contained in tobacco smoke accumulate on the teeth and soft tissues of the smoker's mouth - gums, buccal tissue, tongue. Tobacco use negatively affects the composition of saliva, disrupts its pH, which provokes oral dysbacteriosis and can also cause a fetid odor, in addition, smoking dehydrates the tissues of the oral cavity, which weakens the moisturizing and disinfecting effect of saliva. Pipe and cigar drinkers have more bad breath than cigarette smokers because cigar tobacco contains more sulfur. Breath-freshening toothpastes, mouthwashes, and chewing gums help mask odor, but this is a short-term fix."
}

export const Titles = {
    Asthma: "Asthma",
    LungsCancer: "Lungs Cancer",
    LungCollapse: "Lung Collapse",
    Tuberculosis: "Tuberculosis",
    Tartar: "Tartar",
    YellowTeeth: "Yellow Teeth",
    mouthCancer: "Mouth Cancer",
    GumDiseases: "Gum Diseases",
    Stomatitis: "Stomatitis",
    LossOfTaste: "Loss Of Taste",
    Plaque: "Plaque",
    BadSmell: "Bad Smell"
}

